server:
  port: 8081
cloud:
  aws:
    region:
      auto: false
      static: eu-central-1
    stack:
      auto: false
    queue:
      name: bookInfoQueue
      timeout: 10000
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error